# Generated by Django 3.0.7 on 2020-06-23 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='受注日'),
        ),
    ]
