# Generated by Django 3.0.7 on 2020-06-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200616_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='備考'),
        ),
    ]
