# Generated by Django 3.0.7 on 2020-06-16 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200616_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stock_quantity',
            new_name='quantity',
        ),
    ]
