# Generated by Django 3.0.7 on 2020-06-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200616_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='remarks',
        ),
    ]
